#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# is_done NAME — true if this manual milestone was already marked complete
# on a prior run. Lets re-runs skip stages instead of replaying them.
is_done() { [[ "$(_existing "DONE_${1}")" == "1" ]]; }

# mark_done NAME — record that a manual milestone is complete.
mark_done() {
  local key="DONE_$1" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=1\n' "$key" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

banner "reads.aiste.io — intake setup"

# ── 1. DNS ──────────────────────────────────────────────────────────────
stage "DNS — reads.aiste.io (site) + mail.reads.aiste.io (intake)"
if is_done DNS; then
  note "Already marked done — skipping (delete DONE_DNS from .env to redo)."
else
  say "Two records on the aiste.io zone, both at Namecheap. A CNAME and an MX"
  say "can't coexist at the same name, which is why intake is nested one level"
  say "deeper than the site itself."
  open_url "https://ap.www.namecheap.com/domains/domaincontrolpanel/aiste.io/advancedns"
  step "Add New Record -> CNAME Record: Host = reads, Value = runquest.github.io, TTL = Automatic."
  step "Add New Record -> MX Record: Host = mail.reads, Value = inbound.postmarkapp.com, Priority = 10, TTL = Automatic."
  note "Propagation can take minutes to hours. The Postmark and GitHub Pages steps below both depend on this, so it's worth doing first and letting it settle in the background."
  pause "Press Enter once both records are saved."
  mark_done DNS
fi

# ── 2. Cloudflare login ─────────────────────────────────────────────────
stage "Cloudflare — log in to Wrangler"
say "The intake Worker deploys via Wrangler, Cloudflare's CLI (free tier is enough)."
WHOAMI_OUTPUT=$(npx wrangler whoami 2>&1) || true
printf '%s\n' "$WHOAMI_OUTPUT"
if printf '%s' "$WHOAMI_OUTPUT" | grep -q "You are logged in"; then
  note "Already authenticated — skipping login."
else
  step "Running 'wrangler login' — opens a browser to authorize Cloudflare."
  npx wrangler login
fi

# ── 3. Deploy the Worker ────────────────────────────────────────────────
stage "Cloudflare — deploy the intake Worker"
say "Publishes worker/src/index.js as a live Cloudflare Worker."
DEPLOY_OUTPUT=$(cd worker && npx wrangler deploy 2>&1) || {
  printf '%s\n' "$DEPLOY_OUTPUT"
  warn "Deploy failed — fix the error above and re-run this wizard."
  exit 1
}
printf '%s\n' "$DEPLOY_OUTPUT"
WORKER_URL=$(printf '%s' "$DEPLOY_OUTPUT" | grep -Eo 'https://[a-zA-Z0-9.-]+\.workers\.dev' | head -n1)
if [[ -z "$WORKER_URL" ]]; then
  ask WORKER_URL "Couldn't auto-detect the Worker URL from the output above — paste it (https://...workers.dev):"
fi
write_env WORKER_URL "$WORKER_URL"
note "Worker URL: $WORKER_URL"

# ── 4. Webhook secret ───────────────────────────────────────────────────
stage "Cloudflare — set the intake webhook secret"
if is_done WEBHOOK_SECRET; then
  WEBHOOK_SECRET=$(_existing WEBHOOK_SECRET)
  note "Using saved webhook secret — skipping (delete DONE_WEBHOOK_SECRET from .env to rotate)."
else
  say "The Worker only accepts requests carrying ?secret=... matching this value —"
  say "anyone who doesn't know it gets a 401. This guards the endpoint since it's"
  say "otherwise a public URL."
  DEFAULT_SECRET=$(openssl rand -hex 24 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 48)
  say "Generated: $DEFAULT_SECRET"
  ask WEBHOOK_SECRET "Press Enter to use the generated one above, or paste your own:"
  [[ -z "$WEBHOOK_SECRET" ]] && WEBHOOK_SECRET="$DEFAULT_SECRET"
  write_env WEBHOOK_SECRET "$WEBHOOK_SECRET"
  (cd worker && printf '%s' "$WEBHOOK_SECRET" | npx wrangler secret put WEBHOOK_SECRET)
  mark_done WEBHOOK_SECRET
fi

# ── 5. GitHub PAT for the Worker ────────────────────────────────────────
stage "GitHub — PAT so the Worker can commit raw emails"
if is_done GITHUB_PAT; then
  note "Using saved GitHub PAT — skipping (delete DONE_GITHUB_PAT from .env to rotate)."
else
  say "The Worker writes new raw/ files to this repo via the GitHub API, so it"
  say "needs its own token — scoped to just this repo, contents only."
  open_url "https://github.com/settings/personal-access-tokens/new"
  step "Token name: reads-aiste-io-intake-worker"
  step "Expiration: your choice (e.g. 1 year)"
  step "Repository access -> Only select repositories -> runquest/reads-aiste-io"
  step "Permissions -> Repository permissions -> Contents -> Read and write"
  step "Generate token, then copy it (starts with github_pat_)."
  ask_secret GITHUB_PAT "Paste the token:"
  write_env GITHUB_PAT "$GITHUB_PAT"
  (cd worker && printf '%s' "$GITHUB_PAT" | npx wrangler secret put GITHUB_TOKEN)
  mark_done GITHUB_PAT
fi

# ── 6. Postmark server + inbound domain ─────────────────────────────────
stage "Postmark — server + inbound domain"
if is_done POSTMARK_DOMAIN; then
  INBOUND_LOCAL_PART=$(_existing INBOUND_LOCAL_PART)
  note "Using saved inbound setup (${INBOUND_LOCAL_PART}@mail.reads.aiste.io) — skipping (delete DONE_POSTMARK_DOMAIN from .env to redo)."
else
  say "Postmark receives the forwarded newsletters and POSTs each one to the"
  say "Worker as JSON."
  open_url "https://account.postmarkapp.com/servers"
  step "Create a Server (or pick an existing one) — e.g. name it 'reads-aiste-io'."
  step "Open the server -> Streams tab -> the default Inbound stream -> Settings."
  step "Set the 'Inbound Domain' field to: mail.reads.aiste.io"
  note "Docs call this field InboundDomain — exact wording may have shifted since, but it's on the inbound stream's settings page."
  warn "Needs the MX record from stage 1 to have propagated — if you didn't wait, this may not verify yet."
  pause "Press Enter once the Inbound Domain is set and saved."
  ask INBOUND_LOCAL_PART "Local part of the intake address? (e.g. 'newsletters' for newsletters@mail.reads.aiste.io):"
  write_env INBOUND_LOCAL_PART "$INBOUND_LOCAL_PART"
  note "Forward newsletters to: ${INBOUND_LOCAL_PART}@mail.reads.aiste.io"
  mark_done POSTMARK_DOMAIN
fi

# ── 7. Postmark webhook URL ─────────────────────────────────────────────
stage "Postmark — point the inbound webhook at the Worker"
FULL_WEBHOOK_URL="${WORKER_URL}/?secret=${WEBHOOK_SECRET}"
if is_done POSTMARK_WEBHOOK; then
  note "Already pointed at: $FULL_WEBHOOK_URL — skipping (delete DONE_POSTMARK_WEBHOOK from .env to redo)."
else
  say "Still on that same Inbound stream's Settings page."
  step "Find the 'Webhook URL' (InboundHookUrl) field."
  note "Set it to exactly: $FULL_WEBHOOK_URL"
  step "Paste that exact URL in, then Save."
  pause "Press Enter once saved."
  mark_done POSTMARK_WEBHOOK
fi

# ── 8. Anthropic API key for the daily compile ──────────────────────────
stage "GitHub Actions — Anthropic API key"
if is_done ANTHROPIC_API_KEY; then
  note "Using saved Anthropic API key — skipping (delete DONE_ANTHROPIC_API_KEY from .env to rotate)."
else
  say "The daily compile workflow (.github/workflows/compile-issue.yml) needs"
  say "this to summarize/categorize articles. Unrelated to intake itself, but"
  say "the pipeline doesn't do anything useful without it."
  open_url "https://console.anthropic.com/settings/keys"
  step "Create (or copy an existing) API key."
  ask_secret ANTHROPIC_API_KEY "Paste the API key:"
  write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
  set_secret ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
  mark_done ANTHROPIC_API_KEY
fi

# ── 9. End-to-end test ───────────────────────────────────────────────────
stage "Test — send a real newsletter through"
say "Forward (or resubscribe) one real newsletter to:"
say "  ${INBOUND_LOCAL_PART}@mail.reads.aiste.io"
note "Postmark inbound processing is usually near-instant once the email arrives."
open_url "https://github.com/runquest/reads-aiste-io/tree/main/raw"
step "Refresh that page after the email lands — you should see a new raw/<date>/*.json file."
if confirm "Did a new file show up in raw/?"; then
  note "Intake pipeline confirmed working end to end."
else
  warn "Check: Postmark's Activity log for the inbound stream, and the Worker's logs (npx wrangler tail, run from worker/)."
fi

finish
